### ISSUE TITLE
Two possible errors in wclip.bash

### ISSUE THREAD

**Issue by daraul** [palortoff/pass-extension-wclip#4]
I installed wclip into ~/.password-store/.extensions/wclip.bash. When I tried pass wclip secret I got the errors below:

/home/me/.password-store/.extensions/wclip.bash: line 6: /dev/clipboard: No such file or directory
/home/me/.password-store/.extensions/wclip.bash: line 7: wclip: command not found
Error: Could not copy data to the clipboard

This is windows 10, if that helps.

**Comment by palortoff** [comment]
I have to admit, I have not used pass under Windows for almost two years now...

How do you use pass under Windows? I developed this extension while using the mingw environment installed with git (git bash). This environment provides the /dev/clipboard device. I do not know if that would be present in other  environments.

To fix the second error you would have to install wclip into a directory that is included in `$path`, or do it the windows way and add the wclip directory to `$path`

**Comment by daraul** [comment]
And this is my first foray into windows in almost 8 :laughing: I found that WSL came with `clip.exe`, which copies things into the Windows clipboard. Maybe `pass-extension-wclip` could be patched to use `clip.exe` instead of `wclip.exe`? I don't know what to do about `/dev/clipboard`, though.

**Comment by palortoff** [comment]
`/dev/clipboard` is used to get the current clipboard content to remove the password after 45 seconds. (copied from the original clip function in `pass`)

To maintain security it would be sufficient to just overwrite the clipboard with a static string. If you don't care about that, just do not clear the password.

I would suggest to create a new extension instead of modifying this one.

**Comment by daraul** [comment]
> I would suggest to create a new extension instead of modifying this one.

I might do just that; doesn't seem difficult to do. I'll close this, then. Doesn't seem like a problem with this extension anyway. 

Thanks for your time.
